# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutMain(object):
    def setupUi(self, aboutMain):
        aboutMain.setObjectName("aboutMain")
        aboutMain.resize(618, 490)
        self.centralwidget = QtWidgets.QWidget(aboutMain)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 40, 611, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 80, 481, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 200, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.fb = QtWidgets.QPushButton(self.centralwidget)
        self.fb.setGeometry(QtCore.QRect(340, 200, 171, 28))
        self.fb.setObjectName("fb")
        self.github = QtWidgets.QPushButton(self.centralwidget)
        self.github.setGeometry(QtCore.QRect(340, 240, 171, 28))
        self.github.setObjectName("github")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 130, 481, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(280, 310, 81, 31))
        self.back.setObjectName("back")
        aboutMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(aboutMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 26))
        self.menubar.setObjectName("menubar")
        aboutMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(aboutMain)
        self.statusbar.setObjectName("statusbar")
        aboutMain.setStatusBar(self.statusbar)

        self.retranslateUi(aboutMain)
        QtCore.QMetaObject.connectSlotsByName(aboutMain)

    def retranslateUi(self, aboutMain):
        _translate = QtCore.QCoreApplication.translate
        aboutMain.setWindowTitle(_translate("aboutMain", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("aboutMain", "THÔNG TIN PHẦN MỀM"))
        self.label_2.setText(_translate("aboutMain", "AUTHOR : HOÀNG MẠNH KHIÊM"))
        self.label_3.setText(_translate("aboutMain", "PHẦN MỀM GIẢI BÀI TOÁN GIẢI TÍCH SỐ"))
        self.fb.setText(_translate("aboutMain", "FACEBOOK "))
        self.github.setText(_translate("aboutMain", "GITHUB"))
        self.label_4.setText(_translate("aboutMain", "Phần mềm viết ra chỉ để qua môn :)))"))
        self.back.setText(_translate("aboutMain", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aboutMain = QtWidgets.QMainWindow()
    ui = Ui_aboutMain()
    ui.setupUi(aboutMain)
    aboutMain.show()
    sys.exit(app.exec_())
