# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'banggiatri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homebanggiatri(object):
    def setupUi(self, homebanggiatri):
        homebanggiatri.setObjectName("homebanggiatri")
        homebanggiatri.resize(601, 474)
        self.banggiatri = QtWidgets.QWidget(homebanggiatri)
        self.banggiatri.setObjectName("banggiatri")
        self.label = QtWidgets.QLabel(self.banggiatri)
        self.label.setGeometry(QtCore.QRect(0, 20, 601, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.banggiatri)
        self.textBrowser.setGeometry(QtCore.QRect(80, 60, 441, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.banggiatri)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 171, 16))
        self.label_2.setObjectName("label_2")
        self.outtable = QtWidgets.QLineEdit(self.banggiatri)
        self.outtable.setGeometry(QtCore.QRect(110, 140, 381, 221))
        self.outtable.setObjectName("outtable")
        self.back = QtWidgets.QPushButton(self.banggiatri)
        self.back.setGeometry(QtCore.QRect(410, 370, 93, 28))
        self.back.setObjectName("back")
        self.label_5 = QtWidgets.QLabel(self.banggiatri)
        self.label_5.setGeometry(QtCore.QRect(80, 70, 441, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.banggiatri)
        self.verticalScrollBar.setGeometry(QtCore.QRect(470, 150, 20, 201))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        homebanggiatri.setCentralWidget(self.banggiatri)
        self.menubar = QtWidgets.QMenuBar(homebanggiatri)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 26))
        self.menubar.setObjectName("menubar")
        homebanggiatri.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(homebanggiatri)
        self.statusbar.setObjectName("statusbar")
        homebanggiatri.setStatusBar(self.statusbar)

        self.retranslateUi(homebanggiatri)
        QtCore.QMetaObject.connectSlotsByName(homebanggiatri)

    def retranslateUi(self, homebanggiatri):
        _translate = QtCore.QCoreApplication.translate
        homebanggiatri.setWindowTitle(_translate("homebanggiatri", "MainWindow"))
        self.label.setText(_translate("homebanggiatri", "BẢNG GIÁ TRỊ"))
        self.label_2.setText(_translate("homebanggiatri", "Bảng giá trị"))
        self.back.setText(_translate("homebanggiatri", "Back"))
        self.label_5.setText(_translate("homebanggiatri", "Copyright 2023 - SKROMNYY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homebanggiatri = QtWidgets.QMainWindow()
    ui = Ui_homebanggiatri()
    ui.setupUi(homebanggiatri)
    homebanggiatri.show()
    sys.exit(app.exec_())
