# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcgauss.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calcgauss(object):
    def setupUi(self, calcgauss):
        calcgauss.setObjectName("calcgauss")
        calcgauss.resize(601, 499)
        self.calc_gauss = QtWidgets.QWidget(calcgauss)
        self.calc_gauss.setObjectName("calc_gauss")
        self.label = QtWidgets.QLabel(self.calc_gauss)
        self.label.setGeometry(QtCore.QRect(0, 20, 601, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.calc_gauss)
        self.textBrowser.setGeometry(QtCore.QRect(70, 60, 441, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.calc_gauss)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 251, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.calc_gauss)
        self.label_4.setGeometry(QtCore.QRect(110, 210, 201, 16))
        self.label_4.setObjectName("label_4")
        self.tinh = QtWidgets.QPushButton(self.calc_gauss)
        self.tinh.setGeometry(QtCore.QRect(350, 280, 141, 28))
        self.tinh.setObjectName("tinh")
        self.back = QtWidgets.QPushButton(self.calc_gauss)
        self.back.setGeometry(QtCore.QRect(410, 390, 93, 28))
        self.back.setObjectName("back")
        self.label_5 = QtWidgets.QLabel(self.calc_gauss)
        self.label_5.setGeometry(QtCore.QRect(80, 70, 441, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.output = QtWidgets.QTextEdit(self.calc_gauss)
        self.output.setGeometry(QtCore.QRect(110, 320, 381, 61))
        self.output.setObjectName("output")
        self.giatritinhgauss = QtWidgets.QTextEdit(self.calc_gauss)
        self.giatritinhgauss.setGeometry(QtCore.QRect(110, 230, 121, 51))
        self.giatritinhgauss.setObjectName("giatritinhgauss")
        self.label_6 = QtWidgets.QLabel(self.calc_gauss)
        self.label_6.setGeometry(QtCore.QRect(110, 300, 141, 16))
        self.label_6.setObjectName("label_6")
        self.giatriheso = QtWidgets.QTextEdit(self.calc_gauss)
        self.giatriheso.setGeometry(QtCore.QRect(110, 130, 381, 81))
        self.giatriheso.setObjectName("giatriheso")
        self.lanlap = QtWidgets.QTextEdit(self.calc_gauss)
        self.lanlap.setGeometry(QtCore.QRect(390, 250, 101, 21))
        self.lanlap.setObjectName("lanlap")
        self.comboBox = QtWidgets.QComboBox(self.calc_gauss)
        self.comboBox.setGeometry(QtCore.QRect(410, 220, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        calcgauss.setCentralWidget(self.calc_gauss)
        self.menubar = QtWidgets.QMenuBar(calcgauss)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 26))
        self.menubar.setObjectName("menubar")
        calcgauss.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calcgauss)
        self.statusbar.setObjectName("statusbar")
        calcgauss.setStatusBar(self.statusbar)

        self.retranslateUi(calcgauss)
        QtCore.QMetaObject.connectSlotsByName(calcgauss)

    def retranslateUi(self, calcgauss):
        _translate = QtCore.QCoreApplication.translate
        calcgauss.setWindowTitle(_translate("calcgauss", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("calcgauss", "PHƯƠNG PHÁP GAUSS"))
        self.label_2.setText(_translate("calcgauss", "Nhập các giá trị hệ số hệ pt dạng Ax=b"))
        self.label_4.setText(_translate("calcgauss", "Nhập giá trị x0"))
        self.tinh.setText(_translate("calcgauss", "Tính"))
        self.back.setText(_translate("calcgauss", "Back"))
        self.label_5.setText(_translate("calcgauss", "Copyright 2023 - SKROMNYY"))
        self.output.setHtml(_translate("calcgauss", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Đáp án sẽ hiện ở đây</p></body></html>"))
        self.label_6.setText(_translate("calcgauss", "Giá trị tại điểm cần tính"))
        self.comboBox.setItemText(0, _translate("calcgauss", "Sai số"))
        self.comboBox.setItemText(1, _translate("calcgauss", "Lần lặp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calcgauss = QtWidgets.QMainWindow()
    ui = Ui_calcgauss()
    ui.setupUi(calcgauss)
    calcgauss.show()
    sys.exit(app.exec_())
