# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcsimpson.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calcsimpson(object):
    def setupUi(self, calcsimpson):
        calcsimpson.setObjectName("calcsimpson")
        calcsimpson.resize(601, 474)
        self.menusimpson = QtWidgets.QWidget(calcsimpson)
        self.menusimpson.setObjectName("menusimpson")
        self.label = QtWidgets.QLabel(self.menusimpson)
        self.label.setGeometry(QtCore.QRect(0, 20, 601, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.menusimpson)
        self.textBrowser.setGeometry(QtCore.QRect(80, 60, 441, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.menusimpson)
        self.label_2.setGeometry(QtCore.QRect(110, 100, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.menusimpson)
        self.label_3.setGeometry(QtCore.QRect(110, 150, 201, 16))
        self.label_3.setObjectName("label_3")
        self.tinh = QtWidgets.QPushButton(self.menusimpson)
        self.tinh.setGeometry(QtCore.QRect(350, 280, 141, 28))
        self.tinh.setObjectName("tinh")
        self.back = QtWidgets.QPushButton(self.menusimpson)
        self.back.setGeometry(QtCore.QRect(410, 370, 93, 28))
        self.back.setObjectName("back")
        self.label_5 = QtWidgets.QLabel(self.menusimpson)
        self.label_5.setGeometry(QtCore.QRect(80, 70, 441, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.menusimpson)
        self.label_6.setGeometry(QtCore.QRect(110, 200, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.menusimpson)
        self.label_7.setGeometry(QtCore.QRect(360, 200, 121, 16))
        self.label_7.setObjectName("label_7")
        self.cantren = QtWidgets.QTextEdit(self.menusimpson)
        self.cantren.setGeometry(QtCore.QRect(110, 170, 141, 21))
        self.cantren.setObjectName("cantren")
        self.canduoi = QtWidgets.QTextEdit(self.menusimpson)
        self.canduoi.setGeometry(QtCore.QRect(110, 220, 141, 21))
        self.canduoi.setObjectName("canduoi")
        self.value_n = QtWidgets.QTextEdit(self.menusimpson)
        self.value_n.setGeometry(QtCore.QRect(340, 220, 141, 21))
        self.value_n.setObjectName("value_n")
        self.imputhamso = QtWidgets.QTextEdit(self.menusimpson)
        self.imputhamso.setGeometry(QtCore.QRect(110, 120, 381, 21))
        self.imputhamso.setObjectName("imputhamso")
        self.label_4 = QtWidgets.QLabel(self.menusimpson)
        self.label_4.setGeometry(QtCore.QRect(110, 290, 221, 16))
        self.label_4.setObjectName("label_4")
        self.output = QtWidgets.QTextEdit(self.menusimpson)
        self.output.setGeometry(QtCore.QRect(110, 310, 381, 41))
        self.output.setObjectName("output")
        calcsimpson.setCentralWidget(self.menusimpson)
        self.menubar = QtWidgets.QMenuBar(calcsimpson)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 26))
        self.menubar.setObjectName("menubar")
        calcsimpson.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calcsimpson)
        self.statusbar.setObjectName("statusbar")
        calcsimpson.setStatusBar(self.statusbar)

        self.retranslateUi(calcsimpson)
        QtCore.QMetaObject.connectSlotsByName(calcsimpson)

    def retranslateUi(self, calcsimpson):
        _translate = QtCore.QCoreApplication.translate
        calcsimpson.setWindowTitle(_translate("calcsimpson", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("calcsimpson", "PHƯƠNG PHÁP SIMPSON"))
        self.label_2.setText(_translate("calcsimpson", "Nhập hàm f(x)"))
        self.label_3.setText(_translate("calcsimpson", "Nhập giá trị cận trên"))
        self.tinh.setText(_translate("calcsimpson", "Tính"))
        self.back.setText(_translate("calcsimpson", "Back"))
        self.label_5.setText(_translate("calcsimpson", "Copyright 2023 - SKROMNYY"))
        self.label_6.setText(_translate("calcsimpson", "Nhập giá trị cận dưới"))
        self.label_7.setText(_translate("calcsimpson", "Nhập khoảng chia n"))
        self.label_4.setText(_translate("calcsimpson", "Tích phân gần đúng của phương trình"))
        self.output.setHtml(_translate("calcsimpson", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Đáp án sẽ hiện ở đây</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calcsimpson = QtWidgets.QMainWindow()
    ui = Ui_calcsimpson()
    ui.setupUi(calcsimpson)
    calcsimpson.show()
    sys.exit(app.exec_())
