# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcdaycung.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calcdaycungg(object):
    def setupUi(self, calcdaycungg):
        calcdaycungg.setObjectName("calcdaycungg")
        calcdaycungg.resize(601, 474)
        self.menudaycung = QtWidgets.QWidget(calcdaycungg)
        self.menudaycung.setObjectName("menudaycung")
        self.label = QtWidgets.QLabel(self.menudaycung)
        self.label.setGeometry(QtCore.QRect(0, 20, 601, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.menudaycung)
        self.textBrowser.setGeometry(QtCore.QRect(80, 60, 441, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.menudaycung)
        self.label_2.setGeometry(QtCore.QRect(110, 100, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.menudaycung)
        self.label_3.setGeometry(QtCore.QRect(110, 150, 201, 16))
        self.label_3.setObjectName("label_3")
        self.tinh = QtWidgets.QPushButton(self.menudaycung)
        self.tinh.setGeometry(QtCore.QRect(350, 280, 141, 28))
        self.tinh.setObjectName("tinh")
        self.back = QtWidgets.QPushButton(self.menudaycung)
        self.back.setGeometry(QtCore.QRect(410, 370, 93, 28))
        self.back.setObjectName("back")
        self.label_5 = QtWidgets.QLabel(self.menudaycung)
        self.label_5.setGeometry(QtCore.QRect(80, 70, 441, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.menudaycung)
        self.label_6.setGeometry(QtCore.QRect(110, 200, 121, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.menudaycung)
        self.comboBox.setGeometry(QtCore.QRect(350, 190, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.imputhamso = QtWidgets.QTextEdit(self.menudaycung)
        self.imputhamso.setGeometry(QtCore.QRect(110, 120, 381, 21))
        self.imputhamso.setObjectName("imputhamso")
        self.cantren = QtWidgets.QTextEdit(self.menudaycung)
        self.cantren.setGeometry(QtCore.QRect(110, 170, 141, 21))
        self.cantren.setObjectName("cantren")
        self.canduoi = QtWidgets.QTextEdit(self.menudaycung)
        self.canduoi.setGeometry(QtCore.QRect(110, 220, 141, 21))
        self.canduoi.setObjectName("canduoi")
        self.valuebombobox = QtWidgets.QTextEdit(self.menudaycung)
        self.valuebombobox.setGeometry(QtCore.QRect(350, 220, 141, 21))
        self.valuebombobox.setObjectName("valuebombobox")
        self.label_4 = QtWidgets.QLabel(self.menudaycung)
        self.label_4.setGeometry(QtCore.QRect(110, 290, 201, 16))
        self.label_4.setObjectName("label_4")
        self.output = QtWidgets.QTextEdit(self.menudaycung)
        self.output.setGeometry(QtCore.QRect(110, 320, 381, 41))
        self.output.setObjectName("output")
        calcdaycungg.setCentralWidget(self.menudaycung)
        self.menubar = QtWidgets.QMenuBar(calcdaycungg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 26))
        self.menubar.setObjectName("menubar")
        calcdaycungg.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calcdaycungg)
        self.statusbar.setObjectName("statusbar")
        calcdaycungg.setStatusBar(self.statusbar)

        self.retranslateUi(calcdaycungg)
        QtCore.QMetaObject.connectSlotsByName(calcdaycungg)

    def retranslateUi(self, calcdaycungg):
        _translate = QtCore.QCoreApplication.translate
        calcdaycungg.setWindowTitle(_translate("calcdaycungg", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("calcdaycungg", "PHƯƠNG PHÁP DÂY CUNG"))
        self.label_2.setText(_translate("calcdaycungg", "Nhập hàm f(x)"))
        self.label_3.setText(_translate("calcdaycungg", "Nhập giá trị cận trên"))
        self.tinh.setText(_translate("calcdaycungg", "Tính"))
        self.back.setText(_translate("calcdaycungg", "Back"))
        self.label_5.setText(_translate("calcdaycungg", "Copyright 2023 - SKROMNYY"))
        self.label_6.setText(_translate("calcdaycungg", "Nhập giá trị cận dưới"))
        self.comboBox.setItemText(0, _translate("calcdaycungg", "Nhập giá trị sai số"))
        self.label_4.setText(_translate("calcdaycungg", "Nghiệm gần đúng của phương trình"))
        self.output.setHtml(_translate("calcdaycungg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Đáp án sẽ hiện ở đây</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calcdaycungg = QtWidgets.QMainWindow()
    ui = Ui_calcdaycungg()
    ui.setupUi(calcdaycungg)
    calcdaycungg.show()
    sys.exit(app.exec_())
