# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dothipt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dothipt(object):
    def setupUi(self, dothipt):
        dothipt.setObjectName("dothipt")
        dothipt.resize(570, 440)
        self.dothi = QtWidgets.QWidget(dothipt)
        self.dothi.setObjectName("dothi")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.dothi)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 70, 491, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.screen = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.screen.setContentsMargins(0, 0, 0, 0)
        self.screen.setObjectName("screen")
        self.label = QtWidgets.QLabel(self.dothi)
        self.label.setGeometry(QtCore.QRect(0, 20, 561, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.dothi)
        self.pushButton.setGeometry(QtCore.QRect(230, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        dothipt.setCentralWidget(self.dothi)
        self.menubar = QtWidgets.QMenuBar(dothipt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 26))
        self.menubar.setObjectName("menubar")
        dothipt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dothipt)
        self.statusbar.setObjectName("statusbar")
        dothipt.setStatusBar(self.statusbar)

        self.retranslateUi(dothipt)
        QtCore.QMetaObject.connectSlotsByName(dothipt)

    def retranslateUi(self, dothipt):
        _translate = QtCore.QCoreApplication.translate
        dothipt.setWindowTitle(_translate("dothipt", "MainWindow"))
        self.label.setText(_translate("dothipt", "ĐỒ THỊ PHƯƠNG TRÌNH"))
        self.pushButton.setText(_translate("dothipt", "Hiển thị"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dothipt = QtWidgets.QMainWindow()
    ui = Ui_dothipt()
    ui.setupUi(dothipt)
    dothipt.show()
    sys.exit(app.exec_())
