# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hdsh.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HDSDMAIN(object):
    def setupUi(self, HDSDMAIN):
        HDSDMAIN.setObjectName("HDSDMAIN")
        HDSDMAIN.resize(618, 490)
        self.centralwidget = QtWidgets.QWidget(HDSDMAIN)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 40, 611, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 80, 481, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 130, 481, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(280, 310, 81, 31))
        self.back.setObjectName("back")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 160, 381, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 200, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 220, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 240, 301, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 260, 321, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 280, 151, 16))
        self.label_9.setObjectName("label_9")
        HDSDMAIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HDSDMAIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 26))
        self.menubar.setObjectName("menubar")
        HDSDMAIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HDSDMAIN)
        self.statusbar.setObjectName("statusbar")
        HDSDMAIN.setStatusBar(self.statusbar)

        self.retranslateUi(HDSDMAIN)
        QtCore.QMetaObject.connectSlotsByName(HDSDMAIN)

    def retranslateUi(self, HDSDMAIN):
        _translate = QtCore.QCoreApplication.translate
        HDSDMAIN.setWindowTitle(_translate("HDSDMAIN", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("HDSDMAIN", "HƯỚNG DẪN SỬ DỤNG"))
        self.label_3.setText(_translate("HDSDMAIN", "PHẦN MỀM GIẢI BÀI TOÁN GIẢI TÍCH SỐ"))
        self.label_4.setText(_translate("HDSDMAIN", "Phần mềm viết ra chỉ để qua môn :))) "))
        self.back.setText(_translate("HDSDMAIN", "BACK"))
        self.label_2.setText(_translate("HDSDMAIN", "Một số quy ước nhập trong xuất trong việc sử dụng phần mềm"))
        self.label_5.setText(_translate("HDSDMAIN", "Số pi = pi"))
        self.label_6.setText(_translate("HDSDMAIN", "Số e = exp(1)"))
        self.label_7.setText(_translate("HDSDMAIN", "Bài toán có thể giải được những pt nhiều tham số"))
        self.label_8.setText(_translate("HDSDMAIN", "Với những bài giải phương trình không có nghiệm từ đầu"))
        self.label_9.setText(_translate("HDSDMAIN", "nếu chọn lặp với số lượng lớn thì sẽ bị responding"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HDSDMAIN = QtWidgets.QMainWindow()
    ui = Ui_HDSDMAIN()
    ui.setupUi(HDSDMAIN)
    HDSDMAIN.show()
    sys.exit(app.exec_())
