# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menunoisuy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menunoisuy_2(object):
    def setupUi(self, menunoisuy_2):
        menunoisuy_2.setObjectName("menunoisuy_2")
        menunoisuy_2.resize(523, 344)
        self.menunoisuy = QtWidgets.QWidget(menunoisuy_2)
        self.menunoisuy.setObjectName("menunoisuy")
        self.textBrowser = QtWidgets.QTextBrowser(self.menunoisuy)
        self.textBrowser.setGeometry(QtCore.QRect(80, 60, 361, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.menunoisuy)
        self.label.setGeometry(QtCore.QRect(0, 30, 521, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pplagrange = QtWidgets.QPushButton(self.menunoisuy)
        self.pplagrange.setGeometry(QtCore.QRect(110, 90, 301, 28))
        self.pplagrange.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pplagrange.setObjectName("pplagrange")
        self.ppnewtoncachdeu = QtWidgets.QPushButton(self.menunoisuy)
        self.ppnewtoncachdeu.setGeometry(QtCore.QRect(110, 120, 301, 28))
        self.ppnewtoncachdeu.setObjectName("ppnewtoncachdeu")
        self.ppnewton = QtWidgets.QPushButton(self.menunoisuy)
        self.ppnewton.setGeometry(QtCore.QRect(110, 150, 301, 28))
        self.ppnewton.setObjectName("ppnewton")
        self.back = QtWidgets.QPushButton(self.menunoisuy)
        self.back.setGeometry(QtCore.QRect(110, 180, 301, 28))
        self.back.setObjectName("back")
        menunoisuy_2.setCentralWidget(self.menunoisuy)
        self.menubar = QtWidgets.QMenuBar(menunoisuy_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 26))
        self.menubar.setObjectName("menubar")
        menunoisuy_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menunoisuy_2)
        self.statusbar.setObjectName("statusbar")
        menunoisuy_2.setStatusBar(self.statusbar)

        self.retranslateUi(menunoisuy_2)
        QtCore.QMetaObject.connectSlotsByName(menunoisuy_2)

    def retranslateUi(self, menunoisuy_2):
        _translate = QtCore.QCoreApplication.translate
        menunoisuy_2.setWindowTitle(_translate("menunoisuy_2", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("menunoisuy_2", "PHƯƠNG PHÁP NỘI SUY"))
        self.pplagrange.setText(_translate("menunoisuy_2", "Nội suy Lagrange"))
        self.ppnewtoncachdeu.setText(_translate("menunoisuy_2", "Nội suy Newton có mốc cách đều"))
        self.ppnewton.setText(_translate("menunoisuy_2", "Nội suy Newton mọi trường hợp"))
        self.back.setText(_translate("menunoisuy_2", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menunoisuy_2 = QtWidgets.QMainWindow()
    ui = Ui_menunoisuy_2()
    ui.setupUi(menunoisuy_2)
    menunoisuy_2.show()
    sys.exit(app.exec_())
