# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lagrange.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calclagra(object):
    def setupUi(self, calclagra):
        calclagra.setObjectName("calclagra")
        calclagra.resize(601, 474)
        self.calc_lagrange = QtWidgets.QWidget(calclagra)
        self.calc_lagrange.setObjectName("calc_lagrange")
        self.label = QtWidgets.QLabel(self.calc_lagrange)
        self.label.setGeometry(QtCore.QRect(0, 20, 601, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.calc_lagrange)
        self.textBrowser.setGeometry(QtCore.QRect(80, 60, 441, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.calc_lagrange)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.calc_lagrange)
        self.label_3.setGeometry(QtCore.QRect(110, 170, 201, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.calc_lagrange)
        self.label_4.setGeometry(QtCore.QRect(110, 220, 201, 16))
        self.label_4.setObjectName("label_4")
        self.tinh = QtWidgets.QPushButton(self.calc_lagrange)
        self.tinh.setGeometry(QtCore.QRect(350, 280, 141, 28))
        self.tinh.setObjectName("tinh")
        self.back = QtWidgets.QPushButton(self.calc_lagrange)
        self.back.setGeometry(QtCore.QRect(410, 370, 93, 28))
        self.back.setObjectName("back")
        self.label_5 = QtWidgets.QLabel(self.calc_lagrange)
        self.label_5.setGeometry(QtCore.QRect(80, 70, 441, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.mocnoisuy = QtWidgets.QTextEdit(self.calc_lagrange)
        self.mocnoisuy.setGeometry(QtCore.QRect(110, 140, 381, 21))
        self.mocnoisuy.setObjectName("mocnoisuy")
        self.giatrimocnoisuy = QtWidgets.QTextEdit(self.calc_lagrange)
        self.giatrimocnoisuy.setGeometry(QtCore.QRect(110, 190, 381, 21))
        self.giatrimocnoisuy.setObjectName("giatrimocnoisuy")
        self.giatrinoisuy = QtWidgets.QTextEdit(self.calc_lagrange)
        self.giatrinoisuy.setGeometry(QtCore.QRect(110, 240, 381, 21))
        self.giatrinoisuy.setObjectName("giatrinoisuy")
        self.label_6 = QtWidgets.QLabel(self.calc_lagrange)
        self.label_6.setGeometry(QtCore.QRect(110, 290, 141, 16))
        self.label_6.setObjectName("label_6")
        self.output = QtWidgets.QTextEdit(self.calc_lagrange)
        self.output.setGeometry(QtCore.QRect(110, 320, 381, 41))
        self.output.setObjectName("output")
        calclagra.setCentralWidget(self.calc_lagrange)
        self.menubar = QtWidgets.QMenuBar(calclagra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 26))
        self.menubar.setObjectName("menubar")
        calclagra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calclagra)
        self.statusbar.setObjectName("statusbar")
        calclagra.setStatusBar(self.statusbar)

        self.retranslateUi(calclagra)
        QtCore.QMetaObject.connectSlotsByName(calclagra)

    def retranslateUi(self, calclagra):
        _translate = QtCore.QCoreApplication.translate
        calclagra.setWindowTitle(_translate("calclagra", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("calclagra", "PHƯƠNG PHÁP LAGRANGE"))
        self.label_2.setText(_translate("calclagra", "Nhập giá trị các mốc nội suy"))
        self.label_3.setText(_translate("calclagra", "Nhập giá trị tại các mốc nội suy"))
        self.label_4.setText(_translate("calclagra", "Nhập giá trị cần tính nội suy"))
        self.tinh.setText(_translate("calclagra", "Tính"))
        self.back.setText(_translate("calclagra", "Back"))
        self.label_5.setText(_translate("calclagra", "Copyright 2023 - SKROMNYY"))
        self.label_6.setText(_translate("calclagra", "Giá trị tại điểm cần tính"))
        self.output.setHtml(_translate("calclagra", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Đáp án sẽ hiện ở đây</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calclagra = QtWidgets.QMainWindow()
    ui = Ui_calclagra()
    ui.setupUi(calclagra)
    calclagra.show()
    sys.exit(app.exec_())
