# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import *
from tkinter import messagebox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 257)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 81, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.taikhoan = QtWidgets.QLineEdit(self.centralwidget)
        self.taikhoan.setGeometry(QtCore.QRect(130, 91, 231, 21))
        self.taikhoan.setText("")
        self.taikhoan.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.taikhoan.setCursorPosition(0)
        self.taikhoan.setObjectName("taikhoan")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(130, 120, 231, 21))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 30, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(90, 170, 81, 41))
        self.login.setObjectName("login")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        self.again = QtWidgets.QPushButton(self.centralwidget)
        self.again.setGeometry(QtCore.QRect(250, 170, 81, 41))
        self.again.setObjectName("again")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 429, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hoàng Mạnh Khiêm VipPro"))
        self.label_2.setText(_translate("MainWindow", "Tài khoản:"))
        self.taikhoan.setPlaceholderText(_translate("MainWindow", "Nhập tài khoản"))
        self.password.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.login.setText(_translate("MainWindow", "Đăng nhập"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu:"))
        self.again.setText(_translate("MainWindow", "Nhập lại"))
        
    #     self.again.clicked.connect(self.reset)
    #     self.login.clicked.connect(lambda: self.log(MainWindow))
    
    # def log(self, dl):
    #     if self.taikhoan.text() == "root" and self.password.text()== "root":
    #         print("Dang nhap thanh cong")
    #         dl.close()
    #         return True
    #     else: 
    #         print("Fail")
    #         messagebox.showwarning("Hoang Manh Khiem VipPro","Nhập sai tài khoản hoặc mật khẩu")
    
    # def reset(self):
    #     self.taikhoan.setText("")
    #     self.password.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
