# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menudaoham.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homedaoham(object):
    def setupUi(self, homedaoham):
        homedaoham.setObjectName("homedaoham")
        homedaoham.resize(523, 344)
        self.menudaoham = QtWidgets.QWidget(homedaoham)
        self.menudaoham.setObjectName("menudaoham")
        self.textBrowser = QtWidgets.QTextBrowser(self.menudaoham)
        self.textBrowser.setGeometry(QtCore.QRect(80, 80, 361, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.menudaoham)
        self.label.setGeometry(QtCore.QRect(0, 30, 521, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ppdaoham = QtWidgets.QPushButton(self.menudaoham)
        self.ppdaoham.setGeometry(QtCore.QRect(110, 120, 301, 28))
        self.ppdaoham.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ppdaoham.setObjectName("ppdaoham")
        self.back = QtWidgets.QPushButton(self.menudaoham)
        self.back.setGeometry(QtCore.QRect(110, 150, 301, 28))
        self.back.setObjectName("back")
        homedaoham.setCentralWidget(self.menudaoham)
        self.menubar = QtWidgets.QMenuBar(homedaoham)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 26))
        self.menubar.setObjectName("menubar")
        homedaoham.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(homedaoham)
        self.statusbar.setObjectName("statusbar")
        homedaoham.setStatusBar(self.statusbar)

        self.retranslateUi(homedaoham)
        QtCore.QMetaObject.connectSlotsByName(homedaoham)

    def retranslateUi(self, homedaoham):
        _translate = QtCore.QCoreApplication.translate
        homedaoham.setWindowTitle(_translate("homedaoham", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("homedaoham", "TÍNH GẦN ĐÚNG ĐẠO HÀM"))
        self.ppdaoham.setText(_translate("homedaoham", "Tính gần đúng đạo hàm"))
        self.back.setText(_translate("homedaoham", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homedaoham = QtWidgets.QMainWindow()
    ui = Ui_homedaoham()
    ui.setupUi(homedaoham)
    homedaoham.show()
    sys.exit(app.exec_())
