# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menutichphan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menunoisuy_2(object):
    def setupUi(self, menunoisuy_2):
        menunoisuy_2.setObjectName("menunoisuy_2")
        menunoisuy_2.resize(523, 344)
        self.menutichphan = QtWidgets.QWidget(menunoisuy_2)
        self.menutichphan.setObjectName("menutichphan")
        self.textBrowser = QtWidgets.QTextBrowser(self.menutichphan)
        self.textBrowser.setGeometry(QtCore.QRect(80, 80, 361, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.menutichphan)
        self.label.setGeometry(QtCore.QRect(0, 30, 521, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pphinhthang = QtWidgets.QPushButton(self.menutichphan)
        self.pphinhthang.setGeometry(QtCore.QRect(110, 100, 301, 28))
        self.pphinhthang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pphinhthang.setObjectName("pphinhthang")
        self.ppsimpson = QtWidgets.QPushButton(self.menutichphan)
        self.ppsimpson.setGeometry(QtCore.QRect(110, 130, 301, 28))
        self.ppsimpson.setObjectName("ppsimpson")
        self.back = QtWidgets.QPushButton(self.menutichphan)
        self.back.setGeometry(QtCore.QRect(110, 160, 301, 28))
        self.back.setObjectName("back")
        menunoisuy_2.setCentralWidget(self.menutichphan)
        self.menubar = QtWidgets.QMenuBar(menunoisuy_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 26))
        self.menubar.setObjectName("menubar")
        menunoisuy_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menunoisuy_2)
        self.statusbar.setObjectName("statusbar")
        menunoisuy_2.setStatusBar(self.statusbar)

        self.retranslateUi(menunoisuy_2)
        QtCore.QMetaObject.connectSlotsByName(menunoisuy_2)

    def retranslateUi(self, menunoisuy_2):
        _translate = QtCore.QCoreApplication.translate
        menunoisuy_2.setWindowTitle(_translate("menunoisuy_2", "Hoàng Mạnh Khiêm VipPro"))
        self.label.setText(_translate("menunoisuy_2", "TÍNH GẦN ĐÚNG TÍCH PHÂN"))
        self.pphinhthang.setText(_translate("menunoisuy_2", "Phương pháp Hình Thang"))
        self.ppsimpson.setText(_translate("menunoisuy_2", "Phương Pháp Simpson"))
        self.back.setText(_translate("menunoisuy_2", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menunoisuy_2 = QtWidgets.QMainWindow()
    ui = Ui_menunoisuy_2()
    ui.setupUi(menunoisuy_2)
    menunoisuy_2.show()
    sys.exit(app.exec_())
